FROM openjdk:8u212-jre
MAINTAINER OreChou orechou1018@gmail.com

COPY fast-auth-1.0-SNAPSHOT.jar /fast/fast-auth-1.0-SNAPSHOT.jar
ENTRYPOINT ["java", "-Xmx256m", "-jar", "/fast/fast-auth-1.0-SNAPSHOT.jar"]